In [9]:
!pip install  watson-machine-learning-client

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 538 kB 4.9 MB/s 
     |████████████████████████████████| 132 kB 71.7 MB/s 
     |████████████████████████████████| 55 kB 5.0 MB/s 
     |████████████████████████████████| 9.9 MB 65.3 MB/s 
     |████████████████████████████████| 79 kB 10.5 MB/s 
     |████████████████████████████████| 140 kB 76.6 MB/s 
     |████████████████████████████████| 956 kB 70.6 MB/s 
     |████████████████████████████████| 135 kB 70.3 MB/s 
     |████████████████████████████████| 62 kB 1.8 MB/s 
  Created wheel for ibm-cos-sdk: filename=ibm_cos_sdk-2.12.0-py3-none-any.whl size=73931 sha256=e71a4f48d5fb8f50d6ae60916180b633ebe3500787c396817f5a28b4655eb443
  Stored in directory: /root/.cache/pip/wheels/ec/94/29/2b57327cf00664b6614304f7958abd29d77ea0e5bbece2ea57
  Created wheel for ibm-cos-sdk-core: filename=ibm_cos_sdk_core-2.12.0-py3-none-any.whl size=562962 sha256=dc188b4852

In [11]:
!pip install ibm_watson_machine_learning
from ibm_watson_machine_learning import APIClient
wml_credentials={
    "url":"https://us-south.ml.cloud.ibm.com",
    "apikey":"azbvzIWIC-IQbBUASvS-rmJGck9151k0YMp72-GMbWpm"
    }
client=APIClient(wml_credentials)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.8 MB 5.0 MB/s 
     |████████████████████████████████| 51 kB 830 kB/s 
     |████████████████████████████████| 824 kB 49.9 MB/s 
     |████████████████████████████████| 133 kB 69.1 MB/s 
     |████████████████████████████████| 547 kB 60.7 MB/s 
  Created wheel for ibm-cos-sdk: filename=ibm_cos_sdk-2.7.0-py2.py3-none-any.whl size=72563 sha256=c49563c3d5267c4bff4f2476b54ce3e307e33917d29736e5582d3475fa62e1d3
  Stored in directory: /root/.cache/pip/wheels/47/22/bf/e1154ff0f5de93cc477acd0ca69abfbb8b799c5b28a66b44c2
  Created wheel for ibm-cos-sdk-core: filename=ibm_cos_sdk_core-2.7.0-py2.py3-none-any.whl size=501013 sha256=8bdcfe509bbc6d271bb4fba3c229ae4ca05b96c72a456de9967c0cc1c712e368
  Stored in directory: /root/.cache/pip/wheels/6c/a2/e4/c16d02f809a3ea998e17cfd02c13369281f3d232aaf5902c19
  Created wheel for ibm-cos-sdk-s3transfer: filename=ibm_cos_

In [12]:
client

In [13]:
def guid_from_space_name(client, space_name):
     space=client.spaces.get_details()
     #print(space)
     return(next(item for item in space['resources'] if item['entity']['name']== space_name)['metadata']['id'])

In [14]:
space_uid=guid_from_space_name(client,'image_classification') #imageclassification is the deployment space name
print("Space UID ="+space_uid)

Space UID =6f0e1104-5419-4a9f-a662-97d85e0ad808


In [1]:
from keras.models import load_model
from keras.preprocessing import image

In [15]:
client.set.default_space(space_uid)

'SUCCESS'

In [16]:
client.repository.download("b13a1e17-c16b-433a-8f40-d94b495b887d", 'nutrition.tar.gz')

Successfully saved model content to file: 'nutrition.tar.gz'


'/content/nutrition.tar.gz'

In [17]:
from keras.models import load_model
from keras.preprocessing import image

In [18]:
model = load_model("nutrition.h5")

In [19]:
import numpy as np

In [20]:
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
#loading of the image
img = load_img("apple.jpg", grayscale=False,target_size=(64,64))
#image to array 
x = img_to_array(img)
#changing the shape
x= np.expand_dims(x,axis = 0)
predict_x=model.predict(x)
classes_x=np.argmax(predict_x,axis = -1)
classes_x

1/1 [==============================] - 0s 55ms/step


array([0])

In [21]:
index=['APPLES', 'BANANA', 'ORANGE', 'PINEAPPLE', 'WATERMELON']
result=str(index[classes_x[0]])
result

'APPLES'

In [22]:
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
#loading of the image
img = load_img("banana.jpg", grayscale=False,target_size=(64,64))
#image to array 
x = img_to_array(img)
#changing the shape
x= np.expand_dims(x,axis = 0)
predict_x=model.predict(x)
classes_x=np.argmax(predict_x,axis = -1)
classes_x

1/1 [==============================] - 0s 15ms/step


array([1])

In [23]:
index=['APPLES', 'BANANA', 'ORANGE', 'PINEAPPLE', 'WATERMELON']
result=str(index[classes_x[0]])
result

'BANANA'

In [31]:
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
#loading of the image
img = load_img("pineapple.jpg", grayscale=False,target_size=(64,64))
#image to array 
x = img_to_array(img)
#changing the shape
x= np.expand_dims(x,axis = 0)
predict_x=model.predict(x)
classes_x=np.argmax(predict_x,axis = -1)
classes_x

1/1 [==============================] - 0s 15ms/step


array([4])

In [30]:
index=['APPLES', 'BANANA', 'ORANGE', 'WATERMELON', 'PINEAPPLE']
result=str(index[classes_x[0]])
result

'PINEAPPLE'